### ISSUE TITLE
ninja error: arch/config/defconfig missing

### ISSUE THREAD

**Issue by tmvkrpxl0** [DotOS/manifest#11]
so I was building dotos rom, and I faced strange error
in normal cases, it should find defconfig in arch/(arch)/config
but it tries to find in arch/config
arch: ARM64
kernel tree: https://github.com/Junak/android_kernel_custom_a6plte
device tree: https://github.com/Junak/android_device_samsung_a6plte
log: https://del.dog/vofafeqeru

**Comment by ghost** [comment]
```a6plte_custom_debug_defconfig``` is is your default kernel config define it in the BoardConfig.mk under kernel section as, 

```TARGET_KERNEL_CONFIG := a6plte_custom_debug_defconfig```

**Comment by chrisschac** [comment]
How could you solve this issue?

**Comment by tmvkrpxl0** [comment]
> How could you solve this issue?

originally, dotos will try to find a corresponding arch for device, but something went wrong for me
so i just hard-coded my architecture directory
