### ISSUE TITLE
Building error.

### ISSUE THREAD

**Issue by megafon929** [DotOS/manifest#12]
Hello. I have been building your rom for Redmi 6A. I had this error.
`building image from target_files RECOVERY...
building image from target_files BOOT...
putting script in bin/install-recovery.sh
cp: после '/home/yarpopkov/dot/out/target/product/cactus/obj/PACKAGING/target_files_intermediates/dot_cactus-target_files-eng.root/IMAGES/' пропущен операнд, задающий целевой файл
По команде «cp --help» можно получить дополнительную информацию.
ninja: build stopped: subcommand failed.
22:18:03 ninja failed with: exit status 1`

`building an image from target_files RECOVERY...
create an image from the target_files download...
entering the script into the system bin/install-recovery.sh
CP: after '/home/yarpopkov/dot/out/target/product/cactus/obj/PACKAGING/target_files_intermediates/dot_cactus-target_files-eng.root / images / ' missing operand specifying target file
The "CP --Help" command provides additional information.
ninja: build stopped: subcommand failed.
22:18: 03 ninja failed: exit state 1`

**Comment by ghost** [comment]
can you show the full log ?
