### ISSUE TITLE
dot.dependencies

### ISSUE THREAD

**Issue by ghost** [DotOS/manifest#13]
i have a error compiling the error is the next:
WARNING: Trying to fetch a device that's already there
Traceback (most recent call last):
  File "build/tools/roomservice.py", line 317, in <module>
    fetch_dependencies(device)
  File "build/tools/roomservice.py", line 272, in fetch_dependencies
    dependencies = parse_dependency_file(location)
  File "build/tools/roomservice.py", line 238, in parse_dependency_file
    raise Exception("ERROR: malformed dependency file")
Exception: ERROR: malformed dependency file
.
the dot.dependencies here:
[
  {
    "repository": "android_hardware_samsung",
    "target_path": "hardware/samsung"
  },
  {
    "repository" : "android_packages_resources_devicesettings",
    "target_path": "packages/resources/devicesettings",
  }
]
.
only i rename the lineage.dependencies, I am new and my English is not that good, but any help is appreciated.

**Comment by mohancm** [comment]
Hey, just clone the required repos manually and delete dependency file.I will fix roomservice by this weekend
