### ISSUE TITLE
Feedbacks regarding dotOS Build of your device!

### ISSUE THREAD

**Issue by XPHXPHL** [DotOS/manifest#19]
Sir, I don't know why it will show me this feedbacks when im building DotOS for my device
here it's

error: system/libhidl/transport/base/1.0/vts/functional/Android.bp:15:1: "vts_ibase_test" depends on undefined module "libinit_test_utils_libraries_defaults"

**Comment by mohancm** [comment]
make sure `system/core` is synced properly.

**Comment by XPHXPHL** [comment]
yes, it's synced properly. Should I sync again?

**Comment by mohancm** [comment]
check if this exists, https://github.com/DotOS/android_system_core/blob/dot11/init/Android.bp#L285

**Comment by Nicede** [comment]
it's same of mine.

**Comment by XPHXPHL** [comment]
i synced again and it dont show me this feedbacks, but it show me another
here it's

FAILED: ninja: dot/out/soong/build.ninja:12854444: multiple rules generate dot/out/soong/vendor-snapshot/arm64/arch-arm64-armv8-a/shared/libthermalclient.so [-w dupbuild=err]

**Comment by mohancm** [comment]
you haven't synced properly or something broke on your end

**Comment by XPHXPHL** [comment]
but it show me this feedback on yesterday. should i delete it and sync again?
