### ISSUE TITLE
Cannot boot for Huawei hi6250

### ISSUE THREAD

**Issue by pomelohan** [DotOS/manifest#2]
Cannot boot for Huawei hi6250.So I want to build dotOS eng version.but how can I build eng version?
Use brunch is userdebug,And I can't see the log
Tree:
https://github.com/Meticulus/android_device_huawei_hi6250
https://github.com/Meticulus/android_kernel_huawei_hi6250
https://github.com/Meticulus/android_vendor_huawei_hi6250

**Comment by Meticulus** [comment]
HAHA
