### ISSUE TITLE
why

### ISSUE THREAD

**Issue by ghost** [DotOS/manifest#21]
vendor/qcom/opensource/commonsys/packages/apps/Bluetooth/jni/com_android_bluetooth_gatt.cpp:2315:21: error: no member named 'TransferSync' in 'BleScannerInterface'
  sGattIf->scanner->TransferSync(str2addr(env,addr), service_data, sync_handle,

**Comment by mohancm** [comment]
we track most of `vendor/qcom` from lineage, and they've merged upstream patches today. so some of the commits were missing in our local repos. now I have picked those patches. it should be fine now. you can sync and compile.

**Comment by ghost** [comment]
> we track most of `vendor/qcom` from lineage, and they've merged upstream patches today. so some of the commits were missing in our local repos. now I have picked those patches. it should be fine now. you can sync and compile.
ok
