### ISSUE TITLE
Facing issue while build DotOS

### ISSUE THREAD

**Issue by buildizer** [DotOS/manifest#24]
Each time it tried to build DotOS i got the same error, I tried to find any solution but I didn't find any this is the error I got on 99% 

`FAILED: /home/os/dotos/out/soong/build.ninja
/home/os/dotos/out/soong/.bootstrap/bin/soong_build -t -l /home/os/dotos/out/.module_paths/Android.bp.list -b /home/os/dotos/out/soong -n /home/os/dotos/out -d /home/os/dotos/out/soong/build.ninja.d -globFile /home/os/dotos/out/soong/.bootstrap/build-globs.ninja -o /home/os/dotos/out/soong/build.ninja Android.bp
error: vendor/dot/build/soong/Android.bp:24:8: module "generated_kernel_includes": cmd: unknown variable '$(PATH_OVERRIDE_SOONG)'
12:17:46 soong bootstrap failed with: exit status 1` 

My environment is like below 
Ram: 32GB 
CPU: 16
OS: Ubuntu 20

**Comment by IacobIonut01** [comment]
This is not a ROM related issue. Check your device tree

**Comment by buildizer** [comment]
I'm tried to build aosp_arm64-eng which it provided by the rom

**Comment by VTVishwanath** [comment]
Got any solution @buildizer  or @IacobIonut01 ?

**Comment by mohancm** [comment]
the generic aosp targets doesn't work. you have either compile for specific device with working sources or build for gsi target using phh sources.
