### ISSUE TITLE
Cant connect to wifi when dotos has already flashed and installed

### ISSUE THREAD

**Issue by PoloDarck** [DotOS/manifest#8]
hi im having a problem
I can't connect to Wi-Fi because when i start the operating system for the first time, its keep thinking and say "searching for Wi-Fi networks" and not even my own Wi-Fi in my house appears
and when and when I try to put in "add a new network" complete with what I ask for the name of the wifi and the password and nothing happens either. 
i installed dotos with android 9 in a j7 2016 model sm-j710MN

**Comment by Darkstar085** [comment]
@PoloDarck Nothing to do with dotos that's device specific issue contact maintainer
