### ISSUE TITLE
Build fails at 99%, cp command error

### ISSUE THREAD

**Issue by arifinsalleh00** [DotOS/manifest#9]
Hi there, I'm building an unofficial build of dotOS pie for the Galaxy S9, all parts of the build process will always go smoothly till it reaches 99%, where it tells me that cp is missing destination file operand ....

https://pastebin.com/HagFkwzf

this is the pastebin that leads up to the build error. Hope someone can take a look at this! I really want to try dotOS for my device :)

**Comment by mohancm** [comment]
Which distro are you using? 
you can try this manually - https://unix.stackexchange.com/questions/481373/how-to-solve-error-of-missing-destination-file-operand-after-sdcard-ngrok-ngro

**Comment by shrekbane** [comment]
> 
> 
> Which distro are you using?
> you can try this manually - https://unix.stackexchange.com/questions/481373/how-to-solve-error-of-missing-destination-file-operand-after-sdcard-ngrok-ngro

I'm using Ubuntu 19.04, 64bit.

So i just run that command before starting the build? Or do i do it after the build?

**Comment by shrekbane** [comment]
@mohancm any idea of what i should place as the destination for the second argument?

**Comment by shrekbane** [comment]
Tried to run the build again but no dice. Same error when it's trying to package target files: /root/android/dot/out/target/product/st...lte/obj/PACKAGING/target_files_intermediates/dot_starlte-target_files-eng.root.zip

I'm not sure of what file to edit to get the cp command to work, and I'm not sure what to copy and where to copy it into as arguments for the command. Any ideas @mohancm @delphij ?

**Comment by shrekbane** [comment]
hi, this is the full build log in case you wanted to take a look at it:)

https://pastebin.com/w48Ei2SY
